import assert from 'node:assert/strict';
import crypto from 'node:crypto';
import {validateAndExtractTimbreFiscalDigital as validate, parseXmlStructure, FiscalErrorSanitizer} from './subject/packages/billing/dist/index.js';
import {ConsumerInboxService,generateFiscalSemanticEventId} from './subject/packages/cloud-server/dist/index.js';
import {createPool} from './sql-runtime/adapter.mjs';
const base='<cfdi:Comprobante xmlns:cfdi="http://www.sat.gob.mx/cfd/4" Version="4.0" Total="116">';
const original=base+'<cfdi:Complemento><p:Pago xmlns:p="urn:payments" Monto="100"/></cfdi:Complemento></cfdi:Comprobante>';
const tfd='<tfd:TimbreFiscalDigital xmlns:tfd="http://www.sat.gob.mx/TimbreFiscalDigital" Version="1.1" UUID="12345678-1234-1234-1234-123456789012" FechaTimbrado="2026-10-02T12:00:00Z" RfcProvCertif="SAT970701NN3" SelloSAT="'+ 'A'.repeat(40)+'" NoCertificadoSAT="30001000000500003416"/>';
const altered=base+'<cfdi:Complemento><p:Pago xmlns:p="urn:payments" Monto="999999"/>'+tfd+'</cfdi:Complemento></cfdi:Comprobante>';
assert.doesNotThrow(()=>validate(altered,{expectedOriginalXml:original,expectedProvider:'SAT970701NN3'}));
console.log('A1 REPRODUCED: changed original fiscal complement Monto=100 to 999999 accepted');
assert.doesNotThrow(()=>parseXmlStructure('<root a="1"b="2">unescaped & text</root>'));
console.log('A2 REPRODUCED: malformed XML missing attribute separator and raw ampersand accepted');
const pool=await createPool();
await pool.query(`CREATE TABLE consumer_inbox_events(id uuid PRIMARY KEY,organization_id uuid,semantic_event_id text,event_kind text,event_contract_version text,consumer_context text,event_payload jsonb,processed_at timestamptz,UNIQUE(organization_id,consumer_context,semantic_event_id)); CREATE TABLE effect(id text PRIMARY KEY);`);
const tenant=crypto.randomUUID(), operation=crypto.randomUUID(), id=generateFiscalSemanticEventId(tenant,operation,'FacturaFiscalEmitida');
const payload={semanticEventId:id,eventContractVersion:'1.0',invoiceId:crypto.randomUUID(),uuid:crypto.randomUUID()};
const event={organizationId:tenant,semanticEventId:id,eventKind:'FacturaFiscalEmitida',eventContractVersion:'1.0',payload,effectMode:'EXTERNAL'};
const inbox=new ConsumerInboxService(pool,{approvalReference:'SIMULATION',maxRestoreHorizonMs:86400000});
let externalCalls=0;
const plan={from:'2026-10-01T00:00:00Z',until:'2026-10-02T00:00:00Z',restoreDomain:'EFFECT_AND_INBOX_RESTORED_TOGETHER',source:{async readInterval(){return {retainedFrom:'2026-01-01T00:00:00Z',retainedUntil:'2027-01-01T00:00:00Z',complete:true,redeliveryIndependentOfAcknowledgment:true,events:[event]}}},handler:async()=>{externalCalls++},verifyEffect:async()=>{throw Error('SQL transaction failure after external effect')}};
await assert.rejects(inbox.processEventWithInbox(tenant,'external',id,event.eventKind,async()=>{externalCalls++},{eventContractVersion:'1.0',payload,effectMode:'EXTERNAL'}),/BLOCKED BY CONTRACT/);
assert.equal(externalCalls,0);
await assert.rejects(inbox.reconcileConsumerRestore(tenant,'external',[event],plan));
await assert.rejects(inbox.reconcileConsumerRestore(tenant,'external',[event],plan));
assert.equal(externalCalls,2);
assert.equal(await inbox.getProcessedEventCount(tenant,'external'),0);
console.log('A3 REPRODUCED: restore invokes EXTERNAL handler twice, both SQL inbox transactions roll back; no durable external idempotency');
await inbox.processEventWithInbox(tenant,'sql',id,event.eventKind,c=>c.query('INSERT INTO effect VALUES ($1)',[id]),{eventContractVersion:'1.0',payload,effectMode:'TRANSACTIONAL_SQL'});
await pool.query('DELETE FROM effect');
let calls=0;
const replay=await inbox.processEventWithInbox(tenant,'sql',id,event.eventKind,async()=>{calls++},{eventContractVersion:'1.0',payload,effectMode:'TRANSACTIONAL_SQL'});
assert.equal(replay.duplicate,true);assert.equal(calls,0);
console.log('A4 REPRODUCED: ordinary redelivery suppresses missing SQL effect when verifyEffect omitted');
for(const s of ['{"password":"CANARY"}','eyJhbGciOiJIUzI1NiJ9.CANARY.signature','password=first\nCANARY','-----BEGIN PRIVATE KEY-----\nCANARY']) assert(!JSON.stringify(FiscalErrorSanitizer.sanitize(new Error(s))).includes('CANARY'));
console.log('A5 PASS: opaque sanitizer removes JSON/JWT/multiline/PEM canaries');
await pool.end();
